### ISSUE TITLE
Object.assign is es2015  function

### ISSUE THREAD

**Issue by mdings** [bitmade/node-twig#1]
Object.assign (line12 of index.js) is unsupported in javascript that is not transpiled

**Comment by bitmade** [comment]
Hi,
sorry for the delay...

In what environment would this be unsupported? I know some browsers don't support Object.assign but this package isn't meant to run in browsers but only in Node environments.
Can you give an example why we'd need to change this?

**Comment by mdings** [comment]
Haha you're absolutely right :) I know I saw an error with the Object.assign function but I am wondering myself now where it came from.
