### ISSUE TITLE
delimiters

### ISSUE THREAD

**Issue by webmobiles** [bitmade/node-twig#16]
Hello;
i've search on the docs, but i've not found how to change delimiters ?  from {{}} to [{ }] ?

**Comment by mamoschli** [comment]
Hi,
this doesn't seem to be easily possible with Twig even if you are using it in plain PHP. It seems you'd have to change some optoins inside the Twig_Lexer which is definitively very advanced and a very special use case. I do not plan to add a feature like this at all but you might be able to achive what you need by forking the repo and changing somethjing inside `Twig.php`:

https://github.com/bitmade/node-twig/tree/master/php
