### ISSUE TITLE
"Command failed" with custom twig filter

### ISSUE THREAD

**Issue by EvanK** [bitmade/node-twig#7]
When I try to add and use a custom twig filter -- [see example here](https://gist.github.com/EvanK/124fd1066fae3e278350c70191eabd69) -- I get the following error:

```js
{ Error: Command failed: php /Users/ekaufman/twig-test/node_modules/exec-php/lib/php/cli.php -p/var/folders/r1/_2bh2l655811g6vp_k_d25pm0000gn/T/tmp-644438slkqo0.2ejc3di.tmp -r/var/folders/r1/_2bh2l655811g6vp_k_d25pm0000gn/T/tmp-6444339j6t05.dua3jtt9.tmp

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 255,
  signal: null,
  cmd: 'php /Users/ekaufman/twig-test/node_modules/exec-php/lib/php/cli.php -p/var/folders/r1/_2bh2l655811g6vp_k_d25pm0000gn/T/tmp-644438slkqo0.2ejc3di.tmp -r/var/folders/r1/_2bh2l655811g6vp_k_d25pm0000gn/T/tmp-6444339j6t05.dua3jtt9.tmp' }
```

Where instead I'd expect it to render:

```
So, you're from Texas
```

**Comment by mamoschli** [comment]
Hi,
running this with Node v6.9.1 gives me the following hint:

`PHP Fatal error:  Uncaught Error: Cannot instantiate abstract class Twig_Filter...`

I looked at the Twig documentation and the version the `node-twig` package uses and found the issue. You need to use the `\Twig_SimpleFilter` class with Twig 1.x.

http://twig.sensiolabs.org/doc/1.x/advanced.html#filters

I'll try to update to version 2 soon, but for now you have to stick to the 1.x features.

**Comment by EvanK** [comment]
Ah, thanks!
